name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Set up gotestfmt
        uses: gotesttools/gotestfmt-action@v2

      - name: Run tests
        run: |
          set -euo pipefail
          go test -json -v -coverprofile=coverage.txt ./... 2>&1 | tee /tmp/gotest.log | gotestfmt

      - name: Upload coverage results
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.txt

  coverage:
    name: Coverage
    needs: unit-test
    runs-on: ubuntu-latest
    permissions:
      contents:      read
      actions:       read
      pull-requests: write
    steps:
      - uses: fgrosse/go-coverage-report@v1.2.0
        with:
          coverage-artifact-name: "coverage"
          coverage-file-name: "coverage.txt"

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Build application
        run: go build -o bin/main cmd/main/main.go

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Run govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run security scan
        run: govulncheck ./...
