name: Update Coverage

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Run tests
        run: |
          go test -coverprofile=coverage.txt $(go list ./... | grep -E '/internal/|/pkg/')

      - name: Upload coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: coverage.txt